// AUTO-GENERATED by scripts/generate-demo-audio.mjs — do not edit by hand.
// A fully rights-clear, zero-upload demo track: the public-domain folk song
// "Frère Jacques", with audio we synthesized ourselves (ElevenLabs TTS) and
// exact word timings derived from the TTS character alignment. Bundling this
// lets a cold visitor experience Listen + Practice end-to-end with no upload,
// and uses no copyrighted recording or cached Musixmatch lyric content.
import type { Track, TrackSession } from "@workspace/api-client-react";

// Sentinel id — real Musixmatch track ids are large positives, so -1 never
// collides. Used to route the demo through bundled data instead of the API.
export const DEMO_TRACK_ID = -1;
const DEMO_AUDIO_PATH = "demo/frere-jacques.mp3";

export const demoTrack: Track = {
  trackId: DEMO_TRACK_ID,
  commontrackId: DEMO_TRACK_ID,
  trackName: "Frère Jacques",
  artistName: "Traditional (public domain)",
  albumName: "Voxara Demo",
  albumCoverUrl: null,
  hasLyrics: true,
  hasRichsync: true,
  hasSubtitles: true,
  hasTranslation: true,
};

export const demoSession: TrackSession = {
  track: demoTrack,
  lines: [
    {
      index: 0,
      ts: 0,
      te: 1.985,
      text: "Frère Jacques, Frère Jacques,",
      translation: "Brother Jacques, Brother Jacques,",
      words: [
        {
          text: "Frère",
          start: 0,
          end: 0.348,
        },
        {
          text: "Jacques,",
          start: 0.395,
          end: 0.859,
        },
        {
          text: "Frère",
          start: 1.103,
          end: 1.451,
        },
        {
          text: "Jacques,",
          start: 1.498,
          end: 1.985,
        },
      ],
    },
    {
      index: 1,
      ts: 2.159,
      te: 4.133,
      text: "Dormez-vous? Dormez-vous?",
      translation: "Are you sleeping? Are you sleeping?",
      words: [
        {
          text: "Dormez-vous?",
          start: 2.159,
          end: 2.949,
        },
        {
          text: "Dormez-vous?",
          start: 3.332,
          end: 4.133,
        },
      ],
    },
    {
      index: 2,
      ts: 4.458,
      te: 6.966,
      text: "Sonnez les matines, sonnez les matines,",
      translation: "Ring the morning bells, ring the morning bells,",
      words: [
        {
          text: "Sonnez",
          start: 4.458,
          end: 4.807,
        },
        {
          text: "les",
          start: 4.841,
          end: 4.934,
        },
        {
          text: "matines,",
          start: 4.969,
          end: 5.608,
        },
        {
          text: "sonnez",
          start: 5.817,
          end: 6.153,
        },
        {
          text: "les",
          start: 6.188,
          end: 6.269,
        },
        {
          text: "matines,",
          start: 6.304,
          end: 6.966,
        },
      ],
    },
    {
      index: 3,
      ts: 7.21,
      te: 12.585,
      text: "Ding, ding, dong. Ding, ding, dong.",
      translation: "Ding, ding, dong. Ding, ding, dong.",
      words: [
        {
          text: "Ding,",
          start: 7.21,
          end: 7.755,
        },
        {
          text: "ding,",
          start: 7.999,
          end: 8.58,
        },
        {
          text: "dong.",
          start: 8.905,
          end: 9.462,
        },
        {
          text: "Ding,",
          start: 9.973,
          end: 10.577,
        },
        {
          text: "ding,",
          start: 10.902,
          end: 11.505,
        },
        {
          text: "dong.",
          start: 11.831,
          end: 12.585,
        },
      ],
    },
  ],
  plainLyrics: null,
  copyright:
    "“Frère Jacques” is a traditional song in the public domain. Audio synthesized by Voxara via ElevenLabs.",
  hasRichsync: true,
  hasTranslation: true,
  syncLevel: "word",
  targetLanguage: "en",
};

export function isDemoTrack(
  track: { trackId: number } | null | undefined,
): boolean {
  return !!track && track.trackId === DEMO_TRACK_ID;
}

// Resolved against the artifact base path (Vite injects the trailing slash).
export function demoAudioUrl(): string {
  return `${import.meta.env.BASE_URL}${DEMO_AUDIO_PATH}`;
}
